"""add_reminder_time_to_medications

Revision ID: 31de214125bf
Revises: 083d5d460ff6
Create Date: 2026-06-25 17:05:50.733909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31de214125bf'
down_revision: Union[str, None] = '083d5d460ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('reminder_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'reminder_time')
    # ### end Alembic commands ###