"""Add is_available to Doctor

Revision ID: b9364f6b3cd8
Revises: 8b1898fa2e01
Create Date: 2026-02-25 21:01:08.556462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9364f6b3cd8'
down_revision: Union[str, None] = '8b1898fa2e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.drop_index('ix_doctors_name', table_name='doctors')
    op.drop_column('doctors', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_doctors_name', 'doctors', ['name'], unique=False)
    op.drop_column('doctors', 'is_available')
    # ### end Alembic commands ###