"""add_user_calendar_tokens_table

Revision ID: d56ea74ee646
Revises: 47e29d5a74a8
Create Date: 2026-06-14 18:40:18.815990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56ea74ee646'
down_revision: Union[str, None] = '47e29d5a74a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_calendar_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('google_email', sa.String(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_calendar_tokens_id'), 'user_calendar_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_calendar_tokens_user_id'), 'user_calendar_tokens', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_calendar_tokens_user_id'), table_name='user_calendar_tokens')
    op.drop_index(op.f('ix_user_calendar_tokens_id'), table_name='user_calendar_tokens')
    op.drop_table('user_calendar_tokens')
    # ### end Alembic commands ###